'use client';
import { useState } from 'react';
import { chartBounds, directionText, numberText as n, zoneText, type StructureAnalysis, type StructureScreen, type Zone } from '@/lib/structure';
const stamp = (v: number) => new Date(v).toLocaleString('pt-BR', {timeZone: 'UTC'}) + ' UTC';
const titles: Record<string,string> = {'1d':'Direção principal · diário','4h':'Região para observar · 4 horas','1h':'Confirmação de entrada · 1 hora'};
const color = (z: Zone) => z.kind==='retracement' ? '#fbbf24' : z.kind==='block' ? '#c4b5fd' : '#38bdf8';
function AnnotatedChart({screen, region}: {screen: StructureScreen; region: Zone | null}) {
  const [layers,setLayers]=useState({zones:true,levels:true,events:true,filled:false});
  const [selected,setSelected]=useState<number | null>(null);
  const candles=screen.candles;
  const zones=layers.zones ? [...screen.zones.filter(z=>layers.filled || !['filled','invalid'].includes(z.status)).slice(-6), ...(region?[region]:[])] : [];
  const {low,high}=chartBounds(candles,zones);
  const w=1120,h=390,left=12,right=102,bottom=34,top=20;
  const step=(w-left-right)/candles.length;
  const x=(i:number)=>left+(i+.5)*step;
  const at=(time:number)=>Math.max(0,candles.findIndex(c=>c.close_time>=time));
  const y=(value:number)=>top+(high-value)/(high-low)*(h-top-bottom);
  const chosen=selected===null?candles.length-1:Math.min(selected,candles.length-1);
  const c=candles[chosen];
  const events=screen.events.filter(e=>e.time===c.close_time);
  const touching=zones.filter(z=>z.confirmed_at<=c.close_time && (!z.ended_at || z.ended_at>=c.close_time) && c.low<=z.high && c.high>=z.low);
  return <div>
    <fieldset className="my-4 flex flex-wrap gap-4 text-sm"><legend className="sr-only">Camadas do gráfico</legend>{([['zones','Regiões'],['levels','Topos e fundos'],['events','Rompimentos e retornos'],['filled','Regiões encerradas']] as const).map(([key,label])=><label key={key} className="flex items-center gap-2"><input type="checkbox" checked={layers[key]} onChange={()=>setLayers({...layers,[key]:!layers[key]})}/>{label}</label>)}</fieldset>
    <div className="overflow-x-auto rounded-lg border border-border bg-[#101827]">
      <svg viewBox={`0 0 ${w} ${h}`} className="min-w-[720px] w-full touch-pan-y" role="img" aria-label="Gráfico de velas fechadas. Regiões amarelas para observar, roxas de reação, azuis de faixas. Selecione uma vela abaixo para os detalhes." onClick={e=>{const rect=e.currentTarget.getBoundingClientRect(); const px=(e.clientX-rect.left)/rect.width*w;setSelected(Math.max(0,Math.min(candles.length-1,Math.floor((px-left)/step))));}}>
        {[0,1,2,3,4].map(i=>{const value=low+(high-low)*i/4;return <g key={i}><line x1={left} x2={w-right} y1={y(value)} y2={y(value)} stroke="#26344a"/><text x={w-right+8} y={y(value)+4} fill="#cbd5e1" fontSize="12">{n(value)}</text></g>;})}
        {zones.map((z,i)=><g key={`${z.kind}-${z.confirmed_at}-${i}`}><title>{zoneText(z)}: {n(z.low)} a {n(z.high)} USDT. Conhecida em {stamp(z.confirmed_at)}.</title><rect x={x(at(z.confirmed_at))} y={y(z.high)} width={Math.max(step,x(z.ended_at?at(z.ended_at):candles.length-1)-x(at(z.confirmed_at)))} height={Math.max(2,y(z.low)-y(z.high))} fill={color(z)} fillOpacity={['invalid','filled'].includes(z.status)?.05:.14} stroke={color(z)} strokeDasharray={['invalid','filled'].includes(z.status)?'2 5':'6 3'}/>{z.midpoint!==undefined && <line x1={x(at(z.confirmed_at))} x2={w-right} y1={y(z.midpoint)} y2={y(z.midpoint)} stroke="#fbbf24" strokeDasharray="2 5"/>}</g>)}
        {layers.levels && screen.pivots.slice(-6).map(p=><g key={`${p.kind}-${p.time}`}><title>{p.kind==='high'?'Topo':'Fundo'} {n(p.price)}. Confirmado em {stamp(p.confirmed_at)}.</title><line x1={x(at(p.confirmed_at))} x2={w-right} y1={y(p.price)} y2={y(p.price)} stroke="#94a3b8" strokeDasharray="2 6"/><circle cx={x(at(p.confirmed_at))} cy={y(p.price)} r="3" fill="#e2e8f0"/></g>)}
        {layers.levels && screen.protected && <line x1={x(at(screen.protected.confirmed_at))} x2={w-right} y1={y(screen.protected.price)} y2={y(screen.protected.price)} stroke="#fb7185" strokeWidth="2"><title>Extremo que protege a direção: {n(screen.protected.price)}</title></line>}
        {candles.map((bar,i)=><g key={bar.time} stroke={bar.close>=bar.open?'#2dd4bf':'#fb923c'} fill={bar.close>=bar.open?'#2dd4bf':'#fb923c'}><line x1={x(i)} x2={x(i)} y1={y(bar.high)} y2={y(bar.low)}/><rect x={x(i)-step*.3} width={Math.max(1,step*.6)} y={y(Math.max(bar.open,bar.close))} height={Math.max(1,Math.abs(y(bar.open)-y(bar.close)))}/></g>)}
        {layers.events && screen.events.slice(-8).map((e,i)=><g key={`${e.kind}-${e.time}-${i}`}><title>{e.label} em {n(e.price)}. Confirmado {stamp(e.time)}.</title><circle cx={x(at(e.time))} cy={y(e.price)} r="8" fill={e.kind==='sweep'?'#fbbf24':'#e2e8f0'}/><text x={x(at(e.time))} y={y(e.price)+3} textAnchor="middle" fill="#0f172a" fontSize="10">{i+1}</text></g>)}
        <line x1={x(chosen)} x2={x(chosen)} y1={top} y2={h-bottom} stroke="#e2e8f0" strokeDasharray="4 4"/>
        {[0,Math.floor(candles.length/2),candles.length-1].map(i=><text key={i} x={Math.min(w-right-90,Math.max(left,x(i)-35))} y={h-10} fill="#cbd5e1" fontSize="11">{new Date(candles[i].time).toLocaleDateString('pt-BR',{timeZone:'UTC'})}</text>)}
      </svg>
    </div>
    <label className="mt-3 block text-sm">Toque no gráfico ou escolha a vela para ver os detalhes<input className="mt-2 w-full" type="range" min="0" max={candles.length-1} value={chosen} onChange={e=>setSelected(Number(e.target.value))}/></label>
    <div aria-live="polite" className="mt-3 rounded-lg bg-muted/30 p-3 text-sm"><p>Fechamento: {stamp(c.close_time)} · {n(c.close)} USDT</p><p className="text-muted-foreground">Abertura {n(c.open)} · máxima {n(c.high)} · mínima {n(c.low)}</p>{events.map((e,i)=><p key={i}>{e.label} em {n(e.price)} USDT.</p>)}{touching.map((z,i)=><p key={i}>{zoneText(z)}: {n(z.low)}–{n(z.high)} USDT.</p>)}</div>
    <p className="mt-3 text-xs text-muted-foreground">Velas verdes: alta; laranjas: baixa. Amarelo: região e metade do impulso; roxo: reação; azul: faixa; rosa: extremo protegido. Pontilhado: topos e fundos. Marcações começam quando foram confirmadas, sem antecipar informação.</p>
    {layers.events && <ol className="mt-3 grid gap-1 text-xs md:grid-cols-2">{screen.events.slice(-8).map((e,i)=><li key={`${e.time}-${i}`}><button className="text-left underline" onClick={()=>setSelected(at(e.time))}>{i+1}. {e.label} · {n(e.price)} · {stamp(e.time)}</button></li>)}</ol>}
  </div>;
}
export function StructurePanel({data,fresh,loading}: {data?: StructureAnalysis; fresh:boolean; loading:boolean}) {
  const [tf,setTf]=useState('4h');
  const available=fresh && data?.state==='available';
  const screen=data?.screens[tf]; const setup=data?.setup;
  return <section id="analysis" className="scroll-mt-24 rounded-xl border border-border bg-card p-5">
    <div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">BTC/USDT · dados reais Binance</p><h2 className="mt-1 text-2xl font-semibold">O que o gráfico mostra</h2><p className="mt-2 text-sm text-muted-foreground">Leitura de estrutura inspirada nas aulas de Alexandre Fornes.</p></div><span className="self-start rounded-full bg-amber-500/10 px-3 py-2 text-sm text-amber-200">{!available?'Aguardando dados válidos':setup?.state==='conditional'?'Plano condicional':setup?.state==='invalid'?'Região invalidada':'Observar e aguardar'}</span></div>
    {loading && <p className="my-6" role="status">Buscando as velas fechadas e calculando as marcações…</p>}
    {!loading && !available && <p className="my-6 text-amber-200" role="alert">{data?.reason || 'A coleta ainda não está válida ou ficou antiga. Aguarde a atualização; não há sinal autorizado.'}</p>}
    {available && screen && setup && <>
      <p className="mt-3 text-xs text-muted-foreground">{data.timeframe_note} Somente velas fechadas. Valores em USDT; horários em UTC.</p>
      <div className="my-5 grid gap-3 md:grid-cols-3">{Object.entries(titles).map(([key,title])=>{const s=data.screens[key];return <button aria-pressed={tf===key} key={key} onClick={()=>setTf(key)} className={`rounded-xl border p-4 text-left ${tf===key?'border-primary bg-primary/5':'border-border'}`}><p className="text-sm">{title}</p><p className="my-2 text-lg font-semibold">{directionText(s.direction)}</p><p className="text-sm text-muted-foreground">{s.description}</p><p className="mt-2 text-xs text-muted-foreground">Movimento mais curto: {directionText(s.internal_direction).toLowerCase()}.</p></button>;})}</div>
      <h3 className="font-semibold">{titles[tf]} · {n(screen.close)} USDT</h3><p className="text-xs text-muted-foreground">Último fechamento: {stamp(screen.close_time)}</p>
      <AnnotatedChart key={tf} screen={screen} region={tf!=='1d'?setup.zone:null}/>
      <div className="my-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-border p-4"><h3 className="font-semibold">O que estamos esperando</h3><p className="mt-2 text-sm">{setup.waiting}</p>{setup.zone && <p className="mt-2 text-sm text-amber-200">Região nas 4 horas: {n(setup.zone.low)} a {n(setup.zone.high)} USDT · {setup.zone.status==='invalid'?'invalidada':'condicional'}.</p>}<p className="mt-2 text-xs text-muted-foreground">Tocar uma região não confirma uma entrada.</p></div><div className="rounded-xl border border-border p-4"><h3 className="font-semibold">Quando essa leitura deixa de valer</h3><p className="mt-2 text-sm">{setup.invalidation}</p>{screen.protected && <p className="mt-2 text-sm">Neste período, um fechamento além de {n(screen.protected.price)} USDT contra a direção indica possível mudança.</p>}</div></div>
      <ul className="grid gap-2 text-sm md:grid-cols-2">{setup.checks.map(c=><li key={c.key} className={c.ok?'text-teal-300':'text-muted-foreground'}>{c.ok?'✓ Confirmado: ':'○ Aguardando: '}{c.text}.</li>)}</ul>
      {setup.plan && <div className="mt-5 rounded-lg border border-amber-400/40 p-4"><h3 className="font-semibold">Plano condicional de estrutura · {directionText(setup.plan.side)}</h3><p className="mt-2 text-sm">Referência {n(setup.plan.entry)} · limite de perda {n(setup.plan.stop)} · alvo anterior {n(setup.plan.target)} USDT.</p><p className="mt-2 text-sm">Retorno / risco: {n(setup.plan.rr)} bruto; {n(setup.plan.net_rr)} após custos estimados. Recalcular se o preço mudar. Este módulo não envia nem agenda operações.</p></div>}
      <details className="mt-6 rounded-lg border border-border p-4 text-sm"><summary className="cursor-pointer font-medium">Como calculamos e quais são os limites</summary><div className="mt-3 space-y-3 text-muted-foreground"><p>Topos e fundos maiores exigem 2 velas de cada lado; os internos exigem 1. O topo só fica conhecido depois dessas velas fecharem. Rompimento de continuação (BOS) exige fechamento; possível mudança (CHoCH) é a perda do extremo protegido, não garantia de reversão.</p><p>A região usa 61,8%–78,6% de devolução do impulso de 4 horas; a linha amarela mostra a metade. Região de reação (order block): última vela oposta entre as 10 anteriores a um rompimento com corpo de pelo menos 1,5 vez a amplitude média das 14 anteriores. É uma aproximação por preço, não prova de ordens institucionais.</p><p>Faixa de três velas (FVG): espaço entre os extremos da primeira e terceira. Uma passagem completa por pavio já conta como preenchimento. Máximas e mínimas próximas, a até 0,15%, são apenas áreas potenciais de interesse.</p><p>A sequência exige continuação anterior, chegada à região, passagem por extremo com retorno, rompimento, faixa ainda aberta e novo retorno no período menor. O plano exige alvo estrutural conhecido com pelo menos 3 vezes o risco líquido, estimando 0,15% de custo por lado. Sem alvo adequado, não criamos um artificial.</p><p>Esta é uma interpretação automática documentada das aulas acessíveis. Não é uma reprodução perfeita nem possui rentabilidade comprovada. Não inferimos intenção de bancos, ondas, fases de mercado ou volume exato negociado por preço. Acumulação periódica é uma decisão separada.</p><p><a href="https://www.youtube.com/playlist?list=PLarwpkrmmCPOZrYeFVGWj4XwcriWlw-f5" target="_blank" rel="noreferrer" className="underline">Consultar as aulas de referência</a> · regra {data.version}.</p></div></details>
    </>}
    <p className="mt-5 text-sm text-muted-foreground">A leitura acima usa estrutura de preço. Os filtros de médias e MACD do Triple Screen são uma estratégia separada, disponível abaixo. A carteira e o teste histórico continuam usando somente esses filtros.</p>
  </section>;
}
